/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Diary;

import myframework.pkgGUIContainers.ClsGUIContainers;

/**
 *
 * @author Win97User
 */
public class DlgGetText extends javax.swing.JDialog {

    public boolean blnDialogAccepted = false;
    /**
     * Creates new form NewJDialog
     */
    private String strText = "";
    static DlgGetText objFrm;
    FrmMain frm;

    public DlgGetText(FrmMain parent, boolean modal) {
        super(parent, modal);
        frm = parent;
        initComponents();
    }

    public static DlgGetText self() {
        if (objFrm == null) {
            objFrm = new DlgGetText(FrmMain.self(), true);
        }
        return objFrm;
    }

    public String fnShow(String strTitle, String strDefaultValue) {
        return fnShowCommonMethod(strTitle, strDefaultValue);
    }

    public String fnShow(String strTitle) {
        return fnShowCommonMethod(strTitle, "");
    }

    private String fnShowCommonMethod(String strTitle, String strDefaultValue) {
        setTitle(strTitle);
        txtText.setText(strDefaultValue);
        ClsGUIContainers.self(frm.txtLogs).fnShowDialogCenter(this, frm, false);
        return strText;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        txtText = new javax.swing.JTextArea();
        cmdok = new javax.swing.JButton();
        cmdCancel = new org.jdesktop.swingx.JXButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        txtText.setColumns(20);
        txtText.setFont(new java.awt.Font("Uni Ila.Sundaram-07", 0, 18)); // NOI18N
        txtText.setRows(5);
        jScrollPane1.setViewportView(txtText);

        cmdok.setText("Ok");
        cmdok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdokActionPerformed(evt);
            }
        });

        cmdCancel.setText("Cancel");
        cmdCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 770, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cmdok)
                .addGap(18, 18, 18)
                .addComponent(cmdCancel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(315, 315, 315))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmdCancel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmdok))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmdokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdokActionPerformed
        // TODO add your handling code here:
        blnDialogAccepted = true;
        strText = txtText.getText();
        this.setVisible(false);
    }//GEN-LAST:event_cmdokActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        txtText.requestFocusInWindow();
    }//GEN-LAST:event_formWindowActivated

    private void cmdCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdCancelActionPerformed
        // TODO add your handling code here:
        strText = "";
        txtText.setText("");
        blnDialogAccepted = false;
        this.setVisible(false);
    }//GEN-LAST:event_cmdCancelActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.jdesktop.swingx.JXButton cmdCancel;
    private javax.swing.JButton cmdok;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtText;
    // End of variables declaration//GEN-END:variables
}
