/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Diary;

import java.awt.event.WindowEvent;
import java.io.File;
import java.io.IOException;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import myframework.pkgDataBase.ClsHSQLDBDataBase;
import myframework.pkgGUIContainers.ClsGUIContainers;

/**
 *
 * @author linuxmintuser02
 */
public class FrmMain extends javax.swing.JFrame {

    public ClsHSQLDBDataBase objDBHSQ;
    public ClsGUIContainers objGUIContainer;
    public DlgLogin objDlg;

    IntFrmJNIHeaderFileCreateAddon objIntFrmJNIHeader;
    IntFrmDiaryReport objIntFrmReport;


    /**
     * Creates new form NewMDIApplication
     */
    public FrmMain() {
        initComponents();
        objDBHSQ = ClsHSQLDBDataBase.self(txtLogs);
        objGUIContainer = ClsGUIContainers.self(txtLogs);
    }

    static FrmMain objFrm;

    public static FrmMain self() {
        if (objFrm == null) {
            objFrm = new FrmMain();
        }
        return objFrm;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtLogs = new javax.swing.JTextArea();
        menuBar = new javax.swing.JMenuBar();
        mnuShowInternalForm01 = new javax.swing.JMenu();
        saveMenuItem = new javax.swing.JMenuItem();
        mnuShowSqlBuilder = new javax.swing.JMenuItem();
        mnuExit = new javax.swing.JMenuItem();
        editMenu = new javax.swing.JMenu();
        mnuSettings = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        mnuHelp = new javax.swing.JMenuItem();
        mnuAbout = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Diary");
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                formComponentResized(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        txtLogs.setColumns(20);
        txtLogs.setRows(5);
        jScrollPane1.setViewportView(txtLogs);

        desktopPane.add(jScrollPane1);
        jScrollPane1.setBounds(0, 0, 930, 270);

        getContentPane().add(desktopPane, java.awt.BorderLayout.CENTER);

        mnuShowInternalForm01.setMnemonic('f');
        mnuShowInternalForm01.setText("Action");

        saveMenuItem.setMnemonic('s');
        saveMenuItem.setText("Report");
        saveMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveMenuItemActionPerformed(evt);
            }
        });
        mnuShowInternalForm01.add(saveMenuItem);

        mnuShowSqlBuilder.setMnemonic('a');
        mnuShowSqlBuilder.setText("SQL Builder");
        mnuShowSqlBuilder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuShowSqlBuilderActionPerformed(evt);
            }
        });
        mnuShowInternalForm01.add(mnuShowSqlBuilder);

        mnuExit.setMnemonic('x');
        mnuExit.setText("Exit");
        mnuExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuExitActionPerformed(evt);
            }
        });
        mnuShowInternalForm01.add(mnuExit);

        menuBar.add(mnuShowInternalForm01);

        editMenu.setMnemonic('e');
        editMenu.setText("Settings");

        mnuSettings.setMnemonic('t');
        mnuSettings.setText("Settings");
        mnuSettings.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuSettingsActionPerformed(evt);
            }
        });
        editMenu.add(mnuSettings);

        menuBar.add(editMenu);

        helpMenu.setMnemonic('h');
        helpMenu.setText("Help");

        mnuHelp.setMnemonic('c');
        mnuHelp.setText("Help");
        mnuHelp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuHelpActionPerformed(evt);
            }
        });
        helpMenu.add(mnuHelp);

        mnuAbout.setMnemonic('a');
        mnuAbout.setText("About");
        mnuAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuAboutActionPerformed(evt);
            }
        });
        helpMenu.add(mnuAbout);

        menuBar.add(helpMenu);

        setJMenuBar(menuBar);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuExitActionPerformed
        this.dispatchEvent(new WindowEvent(this, WindowEvent.WINDOW_CLOSING));
    }//GEN-LAST:event_mnuExitActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            objDlg = DlgLogin.self(this, true);
            objDlg.setVisible(true);

            String strDBPath = "";

            if (System.getProperty("os.name").equals("Linux")) {
                strDBPath = new File(".").getCanonicalPath() + "/resource/TechSupport.db";
            } else {
                strDBPath = new File(".").getCanonicalPath() + "\\resource\\TechSupport.db";
            }
            try {
                objDBHSQ.fnConnectDB("one","", 0, "", "", strDBPath, objDlg.txtUserName.getText(), objDlg.txtPassword.getText());
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(FrmMain.class.getName()).log(Level.SEVERE, null, ex);
                ClsGUIContainers.self(txtLogs).fnDisplayError("Database Open Error : " + ex.getMessage(), "", "");
            } catch (SQLException ex) {
                Logger.getLogger(FrmMain.class.getName()).log(Level.SEVERE, null, ex);
                ClsGUIContainers.self(txtLogs).fnDisplayError("Database Open Error : " + ex.getMessage(), "", "");
            }
            objDlg.dispose();
            objDlg = null;
        } catch (IOException ex) {
            objGUIContainer.fnShowConfirmDialog(this, ex.getMessage(), "Information", JOptionPane.PLAIN_MESSAGE, JOptionPane.ERROR_MESSAGE);
            //Logger.getLogger(FrmMain.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_formWindowOpened

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        if (objGUIContainer.fnShowConfirmDialog(this, "Do you want to close the application?", "Information", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE) == JOptionPane.YES_OPTION) {
            try {
                objDBHSQ.fnCloseDb("one");
            } catch (SQLException ex) {
                Logger.getLogger(FrmMain.class.getName()).log(Level.SEVERE, null, ex);
                ClsGUIContainers.self(txtLogs).fnDisplayError("Database Open Error : " + ex.getMessage(), "", "");
            }
            this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        }

    }//GEN-LAST:event_formWindowClosing

    private void formComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentResized
        // TODO add your handling code here:
        if (objGUIContainer != null) {
            objGUIContainer.fnShowInternalFormMiddle(this.desktopPane, objDlg,false);
        }
    }//GEN-LAST:event_formComponentResized

    private void saveMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveMenuItemActionPerformed
        // TODO add your handling code here:
        objIntFrmReport = IntFrmDiaryReport.self();
        objGUIContainer.fnShowInternalFormCenter(objIntFrmReport, FrmMain.self().desktopPane,false);
    }//GEN-LAST:event_saveMenuItemActionPerformed

    private void mnuShowSqlBuilderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuShowSqlBuilderActionPerformed
        // TODO add your handling code here:
        objIntFrmJNIHeader = IntFrmJNIHeaderFileCreateAddon.self();
        objGUIContainer.fnShowInternalFormCenter(objIntFrmJNIHeader, FrmMain.self().desktopPane,false);        
    }//GEN-LAST:event_mnuShowSqlBuilderActionPerformed

    private void mnuSettingsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuSettingsActionPerformed
        // TODO add your handling code here:
        DlgSettings.self(this,true).setVisible(true);
    }//GEN-LAST:event_mnuSettingsActionPerformed

    private void mnuHelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuHelpActionPerformed
        // TODO add your handling code here:
        DlgHelp.self(this,true).setVisible(true);
    }//GEN-LAST:event_mnuHelpActionPerformed

    private void mnuAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuAboutActionPerformed
        // TODO add your handling code here:
        DlgAbout.self(this,true).setVisible(true);
    }//GEN-LAST:event_mnuAboutActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenu editMenu;
    private javax.swing.JMenu helpMenu;
    public javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem mnuAbout;
    private javax.swing.JMenuItem mnuExit;
    private javax.swing.JMenuItem mnuHelp;
    private javax.swing.JMenuItem mnuSettings;
    private javax.swing.JMenu mnuShowInternalForm01;
    private javax.swing.JMenuItem mnuShowSqlBuilder;
    private javax.swing.JMenuItem saveMenuItem;
    public javax.swing.JTextArea txtLogs;
    // End of variables declaration//GEN-END:variables

}
