/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Diary;

import java.awt.Component;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import myframework.pkgGUIControls.ToolbarInterface;
import myframework.pkgGUIContainers.ClsToolbarOperation;
import myframework.pkgNativeMethods.ClsCreateHeaderFile;
import myframework.pkgNativeMethods.ClsCreateHeaderFile.clsProfile;
import myframework.pkgNativeMethods.ClsCreateHeaderFile.clsProfileData;
import org.jdesktop.swingx.JXLabel;
import org.jdesktop.swingx.JXTextField;

/**
 *
 * @author linuxmintuser02
 */
public class IntFrmJNIHeaderFileCreateAddon extends MyLclJInternalFrame implements ToolbarInterface {
    
    final int NULL_PROFILE_ID = 0;
    DefaultComboBoxModel<String> dcbm = new DefaultComboBoxModel<>();
    ClsCreateHeaderFile cchf = new ClsCreateHeaderFile();
    static IntFrmJNIHeaderFileCreateAddon objFrm;
    ClsTechnologyBL bl;
    
    public static IntFrmJNIHeaderFileCreateAddon self() {
        if (objFrm == null) {
            objFrm = new IntFrmJNIHeaderFileCreateAddon();
        }
        return objFrm;
    }
    
    public IntFrmJNIHeaderFileCreateAddon() {
        initComponents();
        cboProfiles.setModel(dcbm);
        //clsTechnologyBL bl = new ClsTechnologyBL(tblView);
    }

    /**
     * Creates new form InternalForm01
     */
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jXLabel1 = new org.jdesktop.swingx.JXLabel();
        cmdGenerateFiles = new org.jdesktop.swingx.JXButton();
        jXLabel6 = new org.jdesktop.swingx.JXLabel();
        cboProfiles = new javax.swing.JComboBox();
        cmdDeleteProfile = new javax.swing.JButton();
        cmdAddProfile = new javax.swing.JButton();
        pnlSomeCtrls = new org.jdesktop.swingx.JXPanel();
        txtOutputDir = new org.jdesktop.swingx.JXTextField();
        cmdOutDirPath = new org.jdesktop.swingx.JXButton();
        jXLabel2 = new org.jdesktop.swingx.JXLabel();
        txtPkgName = new org.jdesktop.swingx.JXTextField();
        jXLabel3 = new org.jdesktop.swingx.JXLabel();
        txtJavahPath = new org.jdesktop.swingx.JXTextField();
        cmdJavahPath = new org.jdesktop.swingx.JXButton();
        txtJNIHeaderFileName = new org.jdesktop.swingx.JXTextField();
        jXLabel4 = new org.jdesktop.swingx.JXLabel();
        jXLabel5 = new org.jdesktop.swingx.JXLabel();
        txtClsName = new org.jdesktop.swingx.JXTextField();
        jXLabel7 = new org.jdesktop.swingx.JXLabel();
        txtJNISourceFileName = new org.jdesktop.swingx.JXTextField();
        jXLabel8 = new org.jdesktop.swingx.JXLabel();
        txtClassHeaderFileName = new org.jdesktop.swingx.JXTextField();
        jXLabel9 = new org.jdesktop.swingx.JXLabel();
        txtClassSourceFileName = new org.jdesktop.swingx.JXTextField();
        jXLabel10 = new org.jdesktop.swingx.JXLabel();
        txtNameofFiles = new org.jdesktop.swingx.JXTextField();
        chkJNISource = new javax.swing.JCheckBox();
        chkClsHeader = new javax.swing.JCheckBox();
        clsClsSource = new javax.swing.JCheckBox();
        chkJNIHeader = new javax.swing.JCheckBox();
        jXLabel11 = new org.jdesktop.swingx.JXLabel();
        txtClassPath = new org.jdesktop.swingx.JXTextField();
        cmdClsPath = new org.jdesktop.swingx.JXButton();
        optAppendDateTime = new javax.swing.JRadioButton();
        optOverWrite = new javax.swing.JRadioButton();
        cmdSaveProfile = new javax.swing.JButton();
        jXLabel13 = new org.jdesktop.swingx.JXLabel();
        cmdAddProfile1 = new javax.swing.JButton();
        jXLabel12 = new org.jdesktop.swingx.JXLabel();

        setClosable(true);
        setIconifiable(true);
        setTitle("Technology");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jXLabel1.setText("Profile");
        jXLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        getContentPane().add(jXLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 50, 20));

        cmdGenerateFiles.setText("Generate Files");
        cmdGenerateFiles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdGenerateFilesActionPerformed(evt);
            }
        });
        getContentPane().add(cmdGenerateFiles, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 610, -1, -1));

        jXLabel6.setText("jXLabel6");
        getContentPane().add(jXLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 640, -1, -1));

        cboProfiles.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboProfiles.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboProfilesItemStateChanged(evt);
            }
        });
        getContentPane().add(cboProfiles, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, 260, -1));

        cmdDeleteProfile.setText("Delete");
        cmdDeleteProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdDeleteProfileActionPerformed(evt);
            }
        });
        getContentPane().add(cmdDeleteProfile, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 70, 70, -1));

        cmdAddProfile.setText("Create");
        cmdAddProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdAddProfileActionPerformed(evt);
            }
        });
        getContentPane().add(cmdAddProfile, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 70, 70, -1));

        pnlSomeCtrls.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtOutputDir.setPreferredSize(new java.awt.Dimension(205, 20));
        pnlSomeCtrls.add(txtOutputDir, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 50, 470, 30));

        cmdOutDirPath.setText("...");
        cmdOutDirPath.setPreferredSize(new java.awt.Dimension(20, 23));
        pnlSomeCtrls.add(cmdOutDirPath, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 50, 30, 30));

        jXLabel2.setText("JNI Header File Name");
        jXLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        pnlSomeCtrls.add(jXLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 120, 20));

        txtPkgName.setPreferredSize(new java.awt.Dimension(205, 20));
        pnlSomeCtrls.add(txtPkgName, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 130, 470, 30));

        jXLabel3.setText("Output Directory");
        jXLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        pnlSomeCtrls.add(jXLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 110, 20));

        txtJavahPath.setPreferredSize(new java.awt.Dimension(205, 20));
        pnlSomeCtrls.add(txtJavahPath, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, 470, 30));

        cmdJavahPath.setText("...");
        cmdJavahPath.setPreferredSize(new java.awt.Dimension(20, 23));
        pnlSomeCtrls.add(cmdJavahPath, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 10, 30, 30));
        pnlSomeCtrls.add(txtJNIHeaderFileName, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 250, 420, 30));

        jXLabel4.setText("Java Package Name");
        jXLabel4.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        pnlSomeCtrls.add(jXLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 120, 20));

        jXLabel5.setText("Java Class Name");
        jXLabel5.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        pnlSomeCtrls.add(jXLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 110, 20));

        txtClsName.setPreferredSize(new java.awt.Dimension(205, 20));
        pnlSomeCtrls.add(txtClsName, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 170, 470, 30));

        jXLabel7.setText("JNI Source File Name");
        jXLabel7.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        pnlSomeCtrls.add(jXLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, 120, 20));
        pnlSomeCtrls.add(txtJNISourceFileName, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 290, 420, 30));

        jXLabel8.setText("Class Header File Name");
        jXLabel8.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        pnlSomeCtrls.add(jXLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, 120, 20));
        pnlSomeCtrls.add(txtClassHeaderFileName, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 330, 420, 30));

        jXLabel9.setText("Class Source File Name");
        jXLabel9.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        pnlSomeCtrls.add(jXLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, 120, 20));
        pnlSomeCtrls.add(txtClassSourceFileName, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 370, 420, 30));

        jXLabel10.setText("Output File Name");
        jXLabel10.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        pnlSomeCtrls.add(jXLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 120, 20));
        pnlSomeCtrls.add(txtNameofFiles, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 210, 420, 30));

        chkJNISource.setSelected(true);
        pnlSomeCtrls.add(chkJNISource, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 300, -1, -1));

        chkClsHeader.setSelected(true);
        pnlSomeCtrls.add(chkClsHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 340, -1, -1));

        clsClsSource.setSelected(true);
        pnlSomeCtrls.add(clsClsSource, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 380, -1, -1));

        chkJNIHeader.setSelected(true);
        pnlSomeCtrls.add(chkJNIHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 260, -1, -1));

        jXLabel11.setText("Class Path");
        jXLabel11.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        pnlSomeCtrls.add(jXLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 110, 20));

        txtClassPath.setPreferredSize(new java.awt.Dimension(205, 20));
        pnlSomeCtrls.add(txtClassPath, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, 470, 30));

        cmdClsPath.setText("...");
        cmdClsPath.setPreferredSize(new java.awt.Dimension(20, 23));
        pnlSomeCtrls.add(cmdClsPath, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 90, 30, 30));

        buttonGroup1.add(optAppendDateTime);
        optAppendDateTime.setText("Append Date Time");
        pnlSomeCtrls.add(optAppendDateTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 410, -1, 22));

        buttonGroup1.add(optOverWrite);
        optOverWrite.setText("Over Write");
        pnlSomeCtrls.add(optOverWrite, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 410, -1, 22));

        cmdSaveProfile.setText("Save Arguments");
        cmdSaveProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdSaveProfileActionPerformed(evt);
            }
        });
        pnlSomeCtrls.add(cmdSaveProfile, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 410, 140, -1));

        jXLabel13.setText("Javah.exe Path");
        jXLabel13.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        pnlSomeCtrls.add(jXLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 110, 20));

        getContentPane().add(pnlSomeCtrls, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 660, 440));

        cmdAddProfile1.setText("Rename");
        cmdAddProfile1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdAddProfile1ActionPerformed(evt);
            }
        });
        getContentPane().add(cmdAddProfile1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 70, 80, -1));

        jXLabel12.setText("Define Argumens");
        jXLabel12.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jXLabel12.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        getContentPane().add(jXLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 140, 20));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        // TODO add your handling code here:
        //fnLoadAllProfiles();
        fnSetCtrlsEnabled(false);
    }//GEN-LAST:event_formInternalFrameOpened
    
    private void fnLoadAllProfiles() {
        
        clsProfile[] obj = cchf.fnGetAllProfileNames();
        
        if (obj != null) {
            for (clsProfile profile : obj) {
                dcbm.addElement(profile.strProfileName);
            }
            cboProfiles.setSelectedIndex(0);
        }
    }
    
    private void fnLoadProfileData(int intProfileId) {
        clsProfileData obj = cchf.fnGetSelectedProfile(intProfileId);
        if (obj != null) {
            fnAssignProfileDataToGUI(obj);
        }
    }
    
    private void fnAssignProfileDataToGUI(clsProfileData obj) {
        //javah paths arguments
        txtJavahPath.setText(obj.strJavahExePath);
        txtOutputDir.setText(obj.strOutDirPath);
        txtClassPath.setText(obj.strClassPath);
        
        //java class argument
        txtPkgName.setText(obj.strPkgName);
        txtClsName.setText(obj.strClassName);
        
        txtNameofFiles.setText(obj.strNameOfFiles);
        
        //Each file names
        txtJNIHeaderFileName.setText(obj.strJNIHeader);
        txtJNISourceFileName.setText(obj.strJNISource);
        txtClassHeaderFileName.setText(obj.strClassHeader);
        txtClassSourceFileName.setText(obj.strClassSoruce);
        
        //Options
        optOverWrite.setSelected(obj.blnOverWrite);
        optAppendDateTime.setSelected(obj.blnApndDateTime);
    }
    
    private void fnAssignGUItoProfileDataObject(clsProfileData obj) {
        //javah paths arguments
        obj.strJavahExePath = txtJavahPath.getText();
        obj.strOutDirPath = txtOutputDir.getText();
        obj.strClassPath = txtClassPath.getText();
        
        //java class argument
        obj.strPkgName = txtPkgName.getText();
        obj.strClassName = txtClsName.getText();
        
        obj.strNameOfFiles = txtNameofFiles.getText();
        
        //Each file names
        obj.strJNIHeader = txtJNIHeaderFileName.getText();
        obj.strJNISource = txtJNISourceFileName.getText();
        obj.strClassHeader = txtClassHeaderFileName.getText();
        obj.strClassSoruce = txtClassSourceFileName.getText();
        
        //Options
        obj.blnOverWrite  =optOverWrite.isSelected();
        obj.blnApndDateTime = optAppendDateTime.isSelected();
    }
    
    private void fnSetCtrlsEnabled(boolean blnEnabled) {
        Component[] cmp = pnlSomeCtrls.getComponents();
        
        for (Component c : cmp) {
            if (!c.getClass().equals(JXLabel.class)) {
                if (c.getClass().equals(JXTextField.class)) {
                    ((JXTextField) c).setEditable(blnEnabled);
                } else {
                    c.setEnabled(blnEnabled);
                }
            }
        }
    }
    
    private void fnClearAllCtrls() {
        Component[] cmp = pnlSomeCtrls.getComponents();
        for (Component c : cmp) {
            if (!c.getClass().equals(JXTextField.class)) {
                ((JXTextField) c).setText("");
            }
        }
    }

    private void cmdGenerateFilesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdGenerateFilesActionPerformed
        // TODO add your handling code here:
        cchf.fnCreateGetHeaderFileName("D:\\MyApps\\NetBeansProjects\\MyJavaFrameWork\\src\\myframework\\pkgNativeMethods\\ClsCreateHeaderFile.java","D:\\Win_8_1\\PgmFls86\\jdk1.8.0_51\\bin\\javah.exe","C:\\Users\\Win97User\\Desktop\\out",
                "HeaderFileCreator_JNI.h", "D:\\MyApps\\NetBeansProjects\\MyJavaFrameWork\\build\\classes", "myframework.pkgNativeMethods", "ClsCreateHeaderFile", true);
    }//GEN-LAST:event_cmdGenerateFilesActionPerformed

    private void cmdSaveProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdSaveProfileActionPerformed
        // TODO add your handling code here:
        fnSaveProfileDate();
    }//GEN-LAST:event_cmdSaveProfileActionPerformed
    
    private void fnSaveProfileDate() {
        int intProfileID = NULL_PROFILE_ID;
        clsProfileData objProfileData = cchf.new clsProfileData();
        fnAssignGUItoProfileDataObject(objProfileData);
        boolean blnSaved = cchf.fnSaveProfileData(intProfileID, objProfileData);
        fnSetCtrlsEnabled(false);
    }

    private void cmdDeleteProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdDeleteProfileActionPerformed
        // TODO add your handling code here:
        fnDeleteSelectedProfile();
    }//GEN-LAST:event_cmdDeleteProfileActionPerformed
    
    private void fnDeleteSelectedProfile() {
        int intProfileId = NULL_PROFILE_ID;
        if (cchf.fnDeleteProfile(intProfileId)) {
            intProfileId = NULL_PROFILE_ID;
            fnLoadProfileData(intProfileId);
        }
    }

    private void cmdAddProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdAddProfileActionPerformed
        // TODO add your handling code here:
        fnCreateNewProfile();
    }//GEN-LAST:event_cmdAddProfileActionPerformed
    
    private void fnCreateNewProfile() {
        String strProfileName = JOptionPane.showInputDialog("Enter Profile Name");
        int intProfileID = cchf.fnCreateNewProfile(strProfileName);
        if (intProfileID != NULL_PROFILE_ID) {
            fnSetCtrlsEnabled(true);
        } else {
            JOptionPane.showInternalMessageDialog(this, "Error in creating");
        }
    }

    private void cmdAddProfile1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdAddProfile1ActionPerformed
        // TODO add your handling code here:
        fnRenameProfile();
    }//GEN-LAST:event_cmdAddProfile1ActionPerformed

    private void cboProfilesItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboProfilesItemStateChanged
        // TODO add your handling code here:
        int intProfileID = NULL_PROFILE_ID;
        fnLoadProfileData(intProfileID);
    }//GEN-LAST:event_cboProfilesItemStateChanged
    
    private void fnRenameProfile() {
        String strProfileName = JOptionPane.showInputDialog("Enter New Profile Name");
        int intProfileID = NULL_PROFILE_ID;
        if (!cchf.fnRenameProfile(intProfileID, strProfileName)) {
            JOptionPane.showInternalMessageDialog(this, "Error in renaming the profile");
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox cboProfiles;
    private javax.swing.JCheckBox chkClsHeader;
    private javax.swing.JCheckBox chkJNIHeader;
    private javax.swing.JCheckBox chkJNISource;
    private javax.swing.JCheckBox clsClsSource;
    private javax.swing.JButton cmdAddProfile;
    private javax.swing.JButton cmdAddProfile1;
    private org.jdesktop.swingx.JXButton cmdClsPath;
    private javax.swing.JButton cmdDeleteProfile;
    private org.jdesktop.swingx.JXButton cmdGenerateFiles;
    private org.jdesktop.swingx.JXButton cmdJavahPath;
    private org.jdesktop.swingx.JXButton cmdOutDirPath;
    private javax.swing.JButton cmdSaveProfile;
    private org.jdesktop.swingx.JXLabel jXLabel1;
    private org.jdesktop.swingx.JXLabel jXLabel10;
    private org.jdesktop.swingx.JXLabel jXLabel11;
    private org.jdesktop.swingx.JXLabel jXLabel12;
    private org.jdesktop.swingx.JXLabel jXLabel13;
    private org.jdesktop.swingx.JXLabel jXLabel2;
    private org.jdesktop.swingx.JXLabel jXLabel3;
    private org.jdesktop.swingx.JXLabel jXLabel4;
    private org.jdesktop.swingx.JXLabel jXLabel5;
    private org.jdesktop.swingx.JXLabel jXLabel6;
    private org.jdesktop.swingx.JXLabel jXLabel7;
    private org.jdesktop.swingx.JXLabel jXLabel8;
    private org.jdesktop.swingx.JXLabel jXLabel9;
    private javax.swing.JRadioButton optAppendDateTime;
    private javax.swing.JRadioButton optOverWrite;
    private org.jdesktop.swingx.JXPanel pnlSomeCtrls;
    private org.jdesktop.swingx.JXTextField txtClassHeaderFileName;
    private org.jdesktop.swingx.JXTextField txtClassPath;
    private org.jdesktop.swingx.JXTextField txtClassSourceFileName;
    private org.jdesktop.swingx.JXTextField txtClsName;
    private org.jdesktop.swingx.JXTextField txtJNIHeaderFileName;
    private org.jdesktop.swingx.JXTextField txtJNISourceFileName;
    private org.jdesktop.swingx.JXTextField txtJavahPath;
    private org.jdesktop.swingx.JXTextField txtNameofFiles;
    private org.jdesktop.swingx.JXTextField txtOutputDir;
    private org.jdesktop.swingx.JXTextField txtPkgName;
    // End of variables declaration//GEN-END:variables

    @Override
    public void fnAddNewRecordEvent(ClsToolbarOperation obj, int subCommand, int flagReserved) {
        
    }
    
    @Override
    public void fnEditExitingRecordEvent(ClsToolbarOperation obj, int subCommand, int flagReserved) {
        
    }
    
    @Override
    public void fnSaveNewRecordEvent(ClsToolbarOperation obj, int subCommand, int flagReserved) {
        
    }
    
    @Override
    public void fnReloadEvent(ClsToolbarOperation obj, int subCommand, int flagReserved) {
        
    }
    
    @Override
    public void fnSaveExistingRecordEvent(ClsToolbarOperation obj, int subCommand, int flagReserved) {
        
    }
    
    @Override
    public void fnClearEvent(ClsToolbarOperation obj, int subCommand, int flagReserved) {
        
    }
    
    @Override
    public void fnCancelEvent(ClsToolbarOperation obj, int subCommand, int flagReserved) {
        
    }
    
    @Override
    public void fnCloseEvent(ClsToolbarOperation obj, int subCommand, int flagReserved) {
        // obj.blnCancelInbuildProcess=true;
    }
    
    @Override
    public void fnDeleteRecordEvent(ClsToolbarOperation obj, int subCommand, int flagReserved) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
    
}
